#!/bin/sh
set -e

IMAGE=davidcardoso/aws-sso-cred:latest

echo "=========================================================="
echo "Building '${IMAGE}'..."
echo "=========================================================="

docker build \
    --platform linux/amd64 \
    --tag ${IMAGE} .
